### PR TITLE
add missing build scripts

### PR DESCRIPTION
**Pull request by mirchr**
The required build scripts are not in master.

### CODE REVIEW

**Comment by UlricE** [comment]
Hi, I don't think there is any reason add these autogenerated intermediate files, especially with the build script you contributed a few days ago.

**Comment by mirchr** [comment]
Can we update the INSTALL file to execute the bootstrap.sh script? The instructions currently state to execute ./configure which does not exist any more in master.

**Comment by mirchr** [comment]
removed the build scripts and updated INSTALL. Please review.

**Comment by UlricE** [comment]
Done!

**Pull request merged**
